const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('stealth', {
  getState: () => ipcRenderer.invoke('get-state'),
  setOpacity: (v) => ipcRenderer.send('set-opacity', v),
  saveUrl: (url) => ipcRenderer.send('save-url', url),
  toggleHidden: () => ipcRenderer.send('toggle-hidden'),
  setAlwaysOnTop: (on) => ipcRenderer.send('set-always-on-top', on),
  setSpeed: (r) => ipcRenderer.send('set-speed', r),
  setShowTaskbar: (show) => ipcRenderer.send('set-show-taskbar', show),
  setMuted: (muted) => ipcRenderer.send('set-muted', muted),
  setVolume: (vol) => ipcRenderer.send('set-volume', vol),
  setIgnoreMouse: (ignore) => ipcRenderer.send('set-ignore-mouse', ignore),
  saveCustom: (settings) => ipcRenderer.invoke('save-custom', settings),
  saveToolbar: (tb) => ipcRenderer.invoke('save-toolbar', tb),
  setZoom: (z) => ipcRenderer.send('set-zoom', z),
  selectBackground: () => ipcRenderer.invoke('select-background'),
  clearBackground: () => ipcRenderer.invoke('clear-background'),
  saveExtras: (extras) => ipcRenderer.invoke('save-extras', extras),
  saveUiState: (s) => ipcRenderer.invoke('save-ui-state', s),
  close: () => ipcRenderer.send('window-close'),
  minimize: () => ipcRenderer.send('window-minimize'),
  openMedia: () => ipcRenderer.invoke('open-media'),
  dropTxt: (p) => ipcRenderer.invoke('drop-txt', p),
  filePath: (file) => {
    try { return webUtils.getPathForFile(file); }
    catch (_) { return file && file.path ? file.path : ''; }
  },
  loadProgress: (key) => ipcRenderer.invoke('load-progress', key),
  saveProgress: (key, data) => ipcRenderer.send('save-progress', key, data),
  openTxtPath: (filePath) => ipcRenderer.invoke('open-txt-path', filePath),
  saveHotkeys: (hk) => ipcRenderer.invoke('save-hotkeys', hk),
  addFavorite: (fav) => ipcRenderer.invoke('add-favorite', fav),
  removeFavorite: (url) => ipcRenderer.invoke('remove-favorite', url),
  addHistory: (item) => ipcRenderer.invoke('add-history', item),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  saveSearchSources: (sources) => ipcRenderer.invoke('save-search-sources', sources),
  importSearchSources: (json) => ipcRenderer.invoke('import-search-sources', json),
  exportSearchSources: () => ipcRenderer.invoke('export-search-sources'),
  getBookSources: () => ipcRenderer.invoke('get-book-sources'),
  searchBooks: (sourceIndex, keyword) => ipcRenderer.invoke('search-books', sourceIndex, keyword),
  getChapters: (sourceIndex, bookUrl) => ipcRenderer.invoke('get-chapters', sourceIndex, bookUrl),
  getChapterContent: (sourceIndex, chapterUrl) => ipcRenderer.invoke('get-chapter-content', sourceIndex, chapterUrl),
  novelSearch: (keyword) => ipcRenderer.invoke('novel-search', keyword),
  novelChapters: (book) => ipcRenderer.invoke('novel-chapters', book),
  novelContent: (book, chapter) => ipcRenderer.invoke('novel-content', book, chapter),
  novelExport: (book, chapters) => ipcRenderer.invoke('novel-export', book, chapters),
  mediaPlayPause: () => ipcRenderer.invoke('media-play-pause'),
  onGlobalHotkey: (cb) => { ipcRenderer.on('hotkey', (_e, name) => cb(name)); },
  onWebviewOpenUrl: (cb) => { ipcRenderer.on('webview-open-url', (_e, url) => cb(url)); },
  onHiddenChanged: (cb) => { ipcRenderer.on('hidden-changed', (_e, hidden) => cb(hidden)); },
  onWindowBlur: (cb) => { ipcRenderer.on('window-blur', () => cb()); },
  onWindowFocus: (cb) => { ipcRenderer.on('window-focus', () => cb()); }
});
